name: Auto-merge Dependabot PRs
on:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main]
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            });
            if (!response.data.merged) {
              throw new Error('Failed to enable auto-merge: ' + response.data.message);
            }
