name: Main Branch Protection

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if PR is from dev branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Pull requests to main branch must come from dev branch only"
            echo "Current source branch: ${{ github.head_ref }}"
            exit 1
          else
            echo "✅ Pull request is from dev branch - proceeding"
          fi

      - name: Validate version bump
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "0.0.0")
          
          echo "Current version: $CURRENT_VERSION"
          echo "Latest tag: $LATEST_TAG"
          
          COMPARISON=$(node -e "
            const semver = require('semver');
            const current = '$CURRENT_VERSION';
            const latest = '$LATEST_TAG';
            if (semver.gt(current, latest)) {
              console.log('valid');
            } else {
              console.log('invalid');
            }
          " 2>/dev/null || echo "valid")
          
          if [ "$COMPARISON" != "valid" ]; then
            echo "❌ Version must be bumped before merging to main"
            echo "Current: $CURRENT_VERSION, Latest: $LATEST_TAG"
            exit 1
          else
            echo "✅ Version has been properly bumped"
          fi
